DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, APELLIDO VARCHAR(100) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, DNI INT NOT NULL, FECHA_INGRESO DATE NOT NULL, DOMICILIO_ID INT NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Lord Cochrane', 209, 'Santiago Centro', 'Santiago'), ('Las Gaviotas', 2309, 'Alerce', 'Puerto Montt');
INSERT INTO PACIENTES (APELLIDO, NOMBRE, DNI, FECHA_INGRESO, DOMICILIO_ID) VALUES ('Abarca', 'Luis', 12345678, '2023-05-24', 1), ('Miguez', 'Ivan', 12345679, '2023-06-10', 2);
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (123456, 'Fernando', 'Gomez'), (789012, 'Mario', 'Rodriguez');